### ISSUE TITLE
Not implemented Exception

### ISSUE THREAD

**Issue by davidatorres** [Microsoft/UnitTestBoilerplateGenerator#39]
### Installed product versions
- Visual Studio: VS2017 Community 15.9.0
- This extension: 1.9.10

### Description
Not implemented Exception, NUnit & Moq options selected

### Steps to recreate
1. Right click on .cs file
2. Click "Create Unit Test Boilerplate..."
3. Error Exception HRESULT 0x80004001 (E_NOTIMPL)
![2018-11-15_10-30-10](https://user-images.githubusercontent.com/10944960/48570806-7344fa80-e8c2-11e8-91e8-806db0c434ea.png)

### Current behavior
Unable to create a boilerplate test file

### Expected behavior
Able to create a boilerplate test file.

**Comment by RandomEngy** [comment]
Thanks for the report. Updated VS to 15.9.0 and saw the error myself.

I think this is an issue with Visual Studio and have opened an issue with them: https://developercommunity.visualstudio.com/content/problem/383952/envdteprojectfilename-throws-notimplementedexcepti.html

**Comment by jszybisz** [comment]
I had the same issue, and finally resolve it.  The problem seems not to be related with VS version. In my case it was collision of some projects in a solution.  I have found out that after creating new class library project (.net framework) it started to work.  You may try to create new solution and add only the project for which you want to generate test classes. This helped in my case. I am working on VS professional 15.9.1 (but the behavior was the same on 15.8.7 and 15.7.4)

**Comment by RandomEngy** [comment]
Do you happen to have an unloaded project in your solution?

**Comment by jszybisz** [comment]
Yes

pt., 16 lis 2018, 20:07: David Rickard <notifications@github.com>
napisał(a):

**Comment by RandomEngy** [comment]
Thanks for confirming. Should be fixed in 1.9.11. I submitted to the marketplace and it's in verification now.
