### ISSUE TITLE
Customize TestMethods template

### ISSUE THREAD

**Issue by MilesLin** [Microsoft/UnitTestBoilerplateGenerator#42]
### Installed product versions
- Visual Studio: 2017 15.9.2 Professional
- This extension: 1.9.12

### Description
I'm using xUnit and NSubstitute to create unit tests.  Is possible to define my own $TestMethods$ variable? 

### Current behavior
Current TestMethods will generate the code below.  It always compiles failed on *TODO* and *Assert.Fail()*, it kind of annoying for me
```
        [Fact]
        public void Post_StateUnderTest_ExpectedBehavior()
        {
            // Arrange
            var unitUnderTest = CreateValuesController();
            string value = TODO;

            // Act
            unitUnderTest.Post(
                value);

            // Assert
            Assert.Fail();
        }
```

### Expected behavior
I will expect to generate the code below.  No compile error.
````
        [Fact]
        public void Post_StateUnderTest_ExpectedBehavior()
        {
            // Arrange
            var unitUnderTest = CreateValuesController();
            string value = "";

            // Act
            unitUnderTest.Post(
                value);

            // Assert
            Assert.True(false, "Not Implement");
        }
```

Miles regards.

**Comment by RandomEngy** [comment]
In 1.9.13 I changed it to use Assert.True(false) for xUnit, so it compiles.

It still inserts TODO for variables; but that is by design. I like to ensure that the value of every variable is considered and eliminate the possibility that some are just left as default because they were neglected (rather that being the correct value to test with). It also puts a big red flag where attention is needed.
