### ISSUE TITLE
FR: Control over code generation

### ISSUE THREAD

**Issue by jeme** [Microsoft/UnitTestBoilerplateGenerator#6]
### Installed product versions
- Visual Studio: 2015 Enterprise. Update 3
- This extension: 1.4.5

### Description
I am not sure if this might already be possible, but I could not find anything that would indicate it.

I would like to be able to have some control over the generated classes, e.g. a templating feature of sorts. The reason being that there is allot in the Boilerplate that we would remove or replace.

The Boilerplace generate code for Moq, but we use AutoMoq on top so the generated code is completely useless to us, so we would rather that it didn't produce this.

Another thing is that it generates SetUp and TearDown's with instance fields and this is just side-effects waiting to happen, there is also strong opinions against them in general as they tend to make tests more difficult to read as you need to understand not one method but 3 to understand the test it self. (Go read The Art of Unit Testing)...

However, the ability to select a full range of classes and then get test classes generated for all those in the right structure is excellent so if we could preserve that we would like to.

**Comment by RandomEngy** [comment]
We've never had any problems with side effects from instance fields since they are all reset after each test. The setup/teardown approach I think is superior to putting the calls in every test (stops you from forgetting a call to .VerifyAll() ), but I can see how if you're using AutoMoq you might not want it.

I did think that some kind of templating system would be good since different teams might have differing approaches to mocking. It was just something I haven't had enough time to research how to do in a robust manner. Another approach might be to detect the presence of the AutoMoq library and alter the default mocking format to use it, and do away with the SetUp/Teardown/instance fields.

I'm not certain when I'll have time to get around to it; but I'd be happy to help out if you wanted to submit a pull request. The templating system might be a bit expensive to implement, but I think you could come up with a new format to use when AutoMoq is detected.

**Comment by jeme** [comment]
@RandomEngy Thats just a statement of "Instance fields does not produce side effects when implemented correctly", and true, erroneous behavior only occur when the implementation has errors.

But the experience is that when instance fields and setup/teardown is introduced to tests, then this happens more often than not as per. developer introduced errors, which is why we don't use that approach. 

When a test setup becomes a hassle to have in each test, in experience the root cause is often that your component under test has become to complex and needs refactoring, but if you insist in not doing that, then factories or builders are the way to go IMO as that is cleaner and makes the the test more readable.

While a templating system is complex to add, I would think that it could help solve many of the cases where different mocking frameworks and test frameworks is used. (And with the right system, I would replace the current logic with that completely and just have some pre-defined templates). Even if it was a simple one which would act as a "I have this template so use that instead" which for now would only have a few replacement properties for name of class under tests etc.

Unfortunately I probably won't have the time to give the Implementation a go as I have many other things on my plate, this was more to ask if there already was such a thing and I just couldn't find it. But now it stands as an idea.

**Comment by RandomEngy** [comment]
Sure, that sounds good like a good philosophy. In practice we've just never seen an error introduced that way.

I do agree that the feature idea has merit.

I'll keep templating/AutoMoq in mind if I ever get a large chunk of free time.

**Comment by RandomEngy** [comment]
Implemented AutoMoq detection and also the ability to set your own custom templates in 1.5.
